settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: hotels_api
  path: .
  commands:
    install:
      status: true
      method: go build -o app ./src/main.go
    run:
      status: true
      method: app -c app.toml
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
